### ISSUE TITLE
Upgrade Tezos to v8.0 

### ISSUE THREAD

**Issue by emmanueldenloye** [tqtezos/homebrew-tq#7]

**Comment by itkach** [comment]
Tezos v 8.0 is around the corner - there's currently rc-2. The formula should be updated accordingly.

**Comment by simonmcl** [comment]
I really need this too. There are breaking changes to Michelson in Edo. I need the client updated to v8.0 so I can experiment and debug the changes

@michaeljklein @emmanueldenloye @weaverine

**Comment by emmanueldenloye** [comment]
@simonmcl Please use the bottles from serokell. You may find them here https://github.com/serokell/tezos-packaging/releases/tag/v8.2-1

Closing issue. Will update README.md to point people to serokell's release page.
